## Importeren van packages

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os
import requests
import plotly.express as px
import plotly.graph_objects as go
import geopandas as gpd

In [2]:
import warnings
warnings.filterwarnings('ignore')

## Importeren van de data

In [3]:
inkomen = pd.read_csv('Inkomen_per_regio.csv', delimiter = ';')

In [4]:
aantal_mensen = pd.read_csv('Aantal_mensen_per_regio.csv', delimiter=';')

In [5]:
opleiding = pd.read_csv('Opleiding_per_regio.csv', delimiter =';')

In [6]:
geo_df=gpd.read_file('provincie_nederland.json')
geo_df['PROV_NAAM']=geo_df['PROV_NAAM'] +str(' (PV)')

In [7]:
# # API
# from urllib.request import urlopen, Request
# response = requests.get("https://data.overheid.nl/community/datarequest/819")
# print(response.status_code)
# print(response.text) # Dit is een stuk tekst
# response.json() # dit is een Python dictionary

## File opschonen

### Inkomen per regio

In [8]:
#MAXIMAAL 1 KEER RUNNEN! Anders worden er kolommen verwijderd die niet verwijderd moeten worden.
# rijen weg halen
inkomen = inkomen.drop(index=0)
inkomen = inkomen.drop(index=14)
inkomen.reset_index(inplace=True)

In [9]:
# komma's vervangen voor punten
inkomen['Inkomen en vermogen|Particuliere huishoudens excl. studenten'] = inkomen['Inkomen en vermogen|Particuliere huishoudens excl. studenten'].str.replace(',', '.')
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Particuliere huishoudens excl. studenten'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Particuliere huishoudens excl. studenten'].str.replace(',', '.')
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenpersoonshuishouden'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenpersoonshuishouden'].str.replace(',', '.')
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenoudergezin'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenoudergezin'].str.replace(',', '.')
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, zonder kind'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, zonder kind'].str.replace(',', '.')
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, met kind(eren)'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, met kind(eren)'].str.replace(',', '.')
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Bron: Inkomen als werknemer'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Bron: Inkomen als werknemer'].str.replace(',', '.')

In [10]:
# type van de kolommen omzetten naar floats
inkomen['Inkomen en vermogen|Particuliere huishoudens excl. studenten'] = inkomen['Inkomen en vermogen|Particuliere huishoudens excl. studenten'].astype(float)
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Particuliere huishoudens excl. studenten'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Particuliere huishoudens excl. studenten'].astype(float)
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenpersoonshuishouden'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenpersoonshuishouden'].astype(float)
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenoudergezin'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenoudergezin'].astype(float)
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, zonder kind'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, zonder kind'].astype(float)
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, met kind(eren)'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, met kind(eren)'].astype(float)
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Bron: Inkomen als werknemer'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Bron: Inkomen als werknemer'].astype(float)

In [11]:
# 'Inkomen en vermogen|Particuliere huishoudens excl. studenten', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Particuliere huishoudens excl. studenten', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenpersoonshuishouden', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenoudergezin', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, zonder kind', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, met kind(eren)', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Bron: Inkomen als werknemer'

In [12]:
# kolommen selecteren
inkomen = inkomen[['Unnamed: 0', 'Inkomen en vermogen|Particuliere huishoudens excl. studenten', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Particuliere huishoudens excl. studenten', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenpersoonshuishouden', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenoudergezin', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, zonder kind', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, met kind(eren)', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Bron: Inkomen als werknemer']]

In [13]:
# namen van kolommen aanpassen
inkomen.rename(columns={'Unnamed: 0': 'provincie',
                        'Inkomen en vermogen|Particuliere huishoudens excl. studenten':'particuliere huishoudens excl. studenten', 
                        'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Particuliere huishoudens excl. studenten':'particuliere huishoudens excl. studenten, gem. besteedbaar inkomen', 
                        'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenpersoonshuishouden': 'eenpersoons- huishouden, gem. besteedbaar inkomen', 
                        'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenoudergezin': 'eenouder- gezin, gem. besteedbaar inkomen',
                        'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, zonder kind': 'paar zonder kind, gem. besteedbaar inkomen', 
                        'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, met kind(eren)':'paar met kinderen, gem. besteedbaar inkomen', 
                        'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Bron: Inkomen als werknemer':'inkomen als werknemer, gem. besteedbaar inkomen' }, inplace = True)

### Aantal mensen per regio
De kleuren zouden overal nog kunnen worden aangepast

In [14]:
# kolommen weg halen
del aantal_mensen["Unnamed: 2"] 
del aantal_mensen["Onderwerp"]
del aantal_mensen['2020']
#rijen weg halen
aantal_mensen = aantal_mensen.drop(index=13)

In [15]:
# kolom namen aanpassen
aantal_mensen.rename(columns={"Regio's": 'provincie',
                             '2019': 'pop_2019'}, inplace=True)

### Opleidingen per regio

In [16]:
# rijen verwijderen
opleiding = opleiding.drop(index=14)
opleiding = opleiding.drop(index=15)
opleiding = opleiding.drop(index=16)
opleiding = opleiding.drop(index=17)
opleiding = opleiding.drop(index=18)
opleiding = opleiding.drop(index=19)
opleiding = opleiding.drop(index=20)
opleiding = opleiding.drop(index=21)
opleiding = opleiding.drop(index=22)
opleiding = opleiding.drop(index=23)
opleiding = opleiding.drop(index=24)
opleiding = opleiding.drop(index=25)
opleiding = opleiding.drop(index=26)
opleiding = opleiding.drop(index=27)
opleiding = opleiding.drop(index=28)
opleiding = opleiding.drop(index=29)
opleiding = opleiding.drop(index=30)
opleiding = opleiding.drop(index=31)

opleiding.reset_index(inplace=True)

In [17]:
# aanpassen de namen van rijen
opleiding.rename(columns={'0': 'provincie'}, inplace = True)

In [18]:
# kolommen selecteren
opleiding = opleiding[['provincie', 'Totaal voortgezet onderwijs (vo)', 'Vavo', 'Totaal mbo (incl. extranei)',
                      'Hbo-associate degree', 'Hbo-bachelor', 'Hbo-master/vervolgopleiding', 'Wo-bachelor',
                      'Wo-master', 'Wo-doctoraal', 'Wo-vervolgopleiding']]

In [19]:
opleiding['Totaal voortgezet onderwijs (vo)'] = opleiding['Totaal voortgezet onderwijs (vo)'].astype(float)
opleiding['Vavo']=opleiding['Vavo'].astype(float)
opleiding['Totaal mbo (incl. extranei)'] = opleiding['Totaal mbo (incl. extranei)'].astype(float)
opleiding['Hbo-associate degree'] = opleiding['Hbo-associate degree'].astype(float)
opleiding['Hbo-bachelor'] = opleiding['Hbo-bachelor'].astype(float)
opleiding['Hbo-master/vervolgopleiding'] = opleiding['Hbo-master/vervolgopleiding'].astype(float)
opleiding['Wo-bachelor'] = opleiding['Wo-bachelor'].astype(float)
opleiding['Wo-master'] = opleiding['Wo-master'].astype(float)
opleiding['Wo-doctoraal'] = opleiding['Wo-doctoraal'].astype(float)
opleiding['Wo-vervolgopleiding'] = opleiding['Wo-vervolgopleiding'].astype(float)

In [20]:
# Opleidingen samenvoegen
opleiding['Hbo'] = opleiding['Hbo-associate degree']+opleiding['Hbo-bachelor']+opleiding['Hbo-master/vervolgopleiding']
opleiding['Hbo']

0     74924.0
1      3549.0
2      2798.0
3      1479.0
4      5491.0
5      1497.0
6      8556.0
7      5746.0
8     10397.0
9     14365.0
10     1210.0
11    12448.0
12     4279.0
13     3109.0
Name: Hbo, dtype: float64

### Geo

In [21]:
geo_df = geo_df[['PROV_NAAM', 'geometry']] # kolommen selecteren

# Dataset mergen
De datasets populatie, inkomen en opleiding worden samengevoegd.

In [22]:
populatie_inkomen = aantal_mensen.merge(inkomen)

In [23]:
df_zondergeo = populatie_inkomen.merge(opleiding)

In [24]:
df=pd.merge(df_zondergeo, geo_df, how = 'inner', left_on = 'provincie', right_on = 'PROV_NAAM', validate = 'many_to_one')

In [25]:
df

,provincie,pop_2019,particuliere huishoudens excl. studenten,"particuliere huishoudens excl. studenten, gem. besteedbaar inkomen","eenpersoons- huishouden, gem. besteedbaar inkomen","eenouder- gezin, gem. besteedbaar inkomen","paar zonder kind, gem. besteedbaar inkomen","paar met kinderen, gem. besteedbaar inkomen","inkomen als werknemer, gem. besteedbaar inkomen",Totaal voortgezet onderwijs (vo),...,Hbo-associate degree,Hbo-bachelor,Hbo-master/vervolgopleiding,Wo-bachelor,Wo-master,Wo-doctoraal,Wo-vervolgopleiding,Hbo,PROV_NAAM,geometry
0,Groningen (PV),583990.0,263.9,39.2,23.6,34.2,44.4,61.2,44.8,5546.0,...,130.0,3245.0,174.0,3122.0,2507.0,0.0,312.0,3549.0,Groningen (PV),"POLYGON ((238550.838 621182.664, 237986.290 62..."
1,Fryslân (PV),647672.0,285.2,41.6,24.2,35.7,44.4,62.2,46.8,7712.0,...,140.0,2494.0,164.0,289.0,314.0,0.0,44.0,2798.0,Fryslân (PV),"POLYGON ((219088.577 615550.321, 219043.135 61..."
2,Drenthe (PV),492167.0,215.8,43.3,24.7,36.2,45.6,63.3,49.5,5885.0,...,110.0,1295.0,74.0,214.0,183.0,0.0,21.0,1479.0,Drenthe (PV),"POLYGON ((229985.506 579739.846, 229780.728 57..."
3,Overijssel (PV),1156431.0,488.1,44.0,24.5,36.2,45.7,64.7,49.3,14597.0,...,169.0,5074.0,248.0,1294.0,1374.0,0.0,151.0,5491.0,Overijssel (PV),"POLYGON ((205507.439 539349.688, 205241.862 53..."
4,Flevoland (PV),416546.0,170.5,45.3,25.3,36.3,48.6,63.4,50.3,5198.0,...,140.0,1305.0,52.0,327.0,286.0,0.0,34.0,1497.0,Flevoland (PV),"POLYGON ((182139.661 535337.499, 182088.641 53..."
5,Gelderland (PV),2071972.0,888.9,45.4,25.2,37.5,48.4,67.2,50.4,24653.0,...,328.0,7854.0,374.0,3797.0,4127.0,0.0,458.0,8556.0,Gelderland (PV),"POLYGON ((192593.176 498989.542, 192161.428 49..."
6,Utrecht (PV),1342158.0,576.6,49.6,27.4,39.9,54.2,74.5,54.2,15782.0,...,162.0,5229.0,355.0,4001.0,4212.0,0.0,503.0,5746.0,Utrecht (PV),"POLYGON ((130188.800 477178.044, 130070.000 47..."
7,Noord-Holland (PV),2853359.0,1312.7,47.1,27.6,38.9,53.5,74.8,52.7,29578.0,...,240.0,9582.0,575.0,6552.0,7507.0,0.0,920.0,10397.0,Noord-Holland (PV),"POLYGON ((154328.670 530832.170, 151670.410 53..."
8,Zuid-Holland (PV),3673893.0,1628.7,45.3,26.2,36.6,50.6,69.8,51.3,38947.0,...,907.0,12601.0,857.0,9532.0,10124.0,0.0,828.0,14365.0,Zuid-Holland (PV),"POLYGON ((97728.934 481002.808, 96586.793 4815..."
9,Zeeland (PV),383032.0,172.4,43.4,25.4,36.5,46.6,65.4,49.4,4078.0,...,93.0,1068.0,49.0,242.0,92.0,0.0,7.0,1210.0,Zeeland (PV),"POLYGON ((50564.929 418784.380, 50331.602 4188..."
10,Noord-Brabant (PV),2544806.0,1113.3,46.3,25.9,38.2,49.0,69.6,51.5,28188.0,...,840.0,11071.0,537.0,3588.0,4254.0,0.0,180.0,12448.0,Noord-Brabant (PV),"POLYGON ((165188.661 425343.807, 164332.809 42..."
11,Limburg (PV),1116137.0,509.7,42.2,24.4,35.9,45.6,64.7,49.1,10369.0,...,205.0,3886.0,188.0,1954.0,1868.0,0.0,200.0,4279.0,Limburg (PV),"POLYGON ((192885.659 417113.722, 192773.960 41..."

## Percentages van opleiding

In [26]:
df['pop_2019']
df.columns

Index(['provincie', 'pop_2019', 'particuliere huishoudens excl. studenten',
       'particuliere huishoudens excl. studenten, gem. besteedbaar inkomen',
       'eenpersoons- huishouden, gem. besteedbaar inkomen',
       'eenouder- gezin, gem. besteedbaar inkomen',
       'paar zonder kind, gem. besteedbaar inkomen',
       'paar met kinderen, gem. besteedbaar inkomen',
       'inkomen als werknemer, gem. besteedbaar inkomen',
       'Totaal voortgezet onderwijs (vo)', 'Vavo',
       'Totaal mbo (incl. extranei)', 'Hbo-associate degree', 'Hbo-bachelor',
       'Hbo-master/vervolgopleiding', 'Wo-bachelor', 'Wo-master',
       'Wo-doctoraal', 'Wo-vervolgopleiding', 'Hbo', 'PROV_NAAM', 'geometry'],
      dtype='object')

In [27]:
df['Totaal voortgezet onderwijs (vo)_p']=df['Totaal voortgezet onderwijs (vo)']/df['pop_2019']*100
df['Totaal mbo (incl. extranei)_p'] = df['Totaal mbo (incl. extranei)']/df['pop_2019']*100
df['Vavo_p'] = df['Vavo']/df['pop_2019']*100
df['Totaal mbo (incl. extranei)_p'] = df['Totaal mbo (incl. extranei)']/df['pop_2019']*100
df['Hbo-associate degree_p'] = df['Hbo-associate degree']/df['pop_2019']*100
df['Hbo-bachelor_p'] = df['Hbo-bachelor']/df['pop_2019']*100
df['Hbo-master/vervolgopleiding_p'] = df['Hbo-master/vervolgopleiding']/df['pop_2019']*100
df['Wo-bachelor_p'] = df['Wo-bachelor']/df['pop_2019']*100
df['Wo-master_p'] = df['Wo-master']/df['pop_2019']*100
df['Wo-doctoraal_p'] = df['Wo-doctoraal']/df['pop_2019']*100
df['Wo-vervolgopleiding_p'] = df['Wo-vervolgopleiding']/df['pop_2019']*100

## Opleidingen samenvoegen
Hbo en Wo

In [28]:
df['Hbo'] = df['Hbo-associate degree']+ df['Hbo-bachelor'] + df['Hbo-master/vervolgopleiding']
df['Wo'] = df['Wo-bachelor']+df['Wo-master']+df['Wo-doctoraal']+df['Wo-vervolgopleiding']
df.head()

,provincie,pop_2019,particuliere huishoudens excl. studenten,"particuliere huishoudens excl. studenten, gem. besteedbaar inkomen","eenpersoons- huishouden, gem. besteedbaar inkomen","eenouder- gezin, gem. besteedbaar inkomen","paar zonder kind, gem. besteedbaar inkomen","paar met kinderen, gem. besteedbaar inkomen","inkomen als werknemer, gem. besteedbaar inkomen",Totaal voortgezet onderwijs (vo),...,Totaal mbo (incl. extranei)_p,Vavo_p,Hbo-associate degree_p,Hbo-bachelor_p,Hbo-master/vervolgopleiding_p,Wo-bachelor_p,Wo-master_p,Wo-doctoraal_p,Wo-vervolgopleiding_p,Wo
0,Groningen (PV),583990.0,263.9,39.2,23.6,34.2,44.4,61.2,44.8,5546.0,...,1.010634,0.040412,0.022261,0.555660,0.029795,0.534598,0.429288,0.0,0.053426,5941.0
1,Fryslân (PV),647672.0,285.2,41.6,24.2,35.7,44.4,62.2,46.8,7712.0,...,1.146414,0.045239,0.021616,0.385071,0.025321,0.044621,0.048481,0.0,0.006794,647.0
2,Drenthe (PV),492167.0,215.8,43.3,24.7,36.2,45.6,63.3,49.5,5885.0,...,1.079512,0.046123,0.022350,0.263122,0.015036,0.043481,0.037183,0.0,0.004267,418.0
3,Overijssel (PV),1156431.0,488.1,44.0,24.5,36.2,45.7,64.7,49.3,14597.0,...,1.107373,0.045744,0.014614,0.438764,0.021445,0.111896,0.118814,0.0,0.013057,2819.0
4,Flevoland (PV),416546.0,170.5,45.3,25.3,36.3,48.6,63.4,50.3,5198.0,...,1.198427,0.048254,0.033610,0.313291,0.012484,0.078503,0.068660,0.0,0.008162,647.0

## Importeren van packages

In [29]:
import pandas as pd
import matplotlib.pyplot as plt
import os
import requests
import plotly.express as px
import plotly.graph_objects as go
import geopandas as gpd

In [30]:
import warnings
warnings.filterwarnings('ignore')

## Importeren van de data

In [31]:
inkomen = pd.read_csv('Inkomen_per_regio.csv', delimiter = ';')

In [32]:
aantal_mensen = pd.read_csv('Aantal_mensen_per_regio.csv', delimiter=';')

In [33]:
opleiding = pd.read_csv('Opleiding_per_regio.csv', delimiter =';')

In [34]:
geo_df=gpd.read_file('provincie_nederland.json')
geo_df['PROV_NAAM']=geo_df['PROV_NAAM'] +str(' (PV)')

In [35]:
# # API
# from urllib.request import urlopen, Request
# response = requests.get("https://data.overheid.nl/community/datarequest/819")
# print(response.status_code)
# print(response.text) # Dit is een stuk tekst
# response.json() # dit is een Python dictionary

## File opschonen

### Inkomen per regio

In [36]:
#MAXIMAAL 1 KEER RUNNEN! Anders worden er kolommen verwijderd die niet verwijderd moeten worden.
# rijen weg halen
inkomen = inkomen.drop(index=0)
inkomen = inkomen.drop(index=14)
inkomen.reset_index(inplace=True)

In [37]:
# komma's vervangen voor punten
inkomen['Inkomen en vermogen|Particuliere huishoudens excl. studenten'] = inkomen['Inkomen en vermogen|Particuliere huishoudens excl. studenten'].str.replace(',', '.')
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Particuliere huishoudens excl. studenten'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Particuliere huishoudens excl. studenten'].str.replace(',', '.')
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenpersoonshuishouden'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenpersoonshuishouden'].str.replace(',', '.')
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenoudergezin'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenoudergezin'].str.replace(',', '.')
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, zonder kind'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, zonder kind'].str.replace(',', '.')
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, met kind(eren)'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, met kind(eren)'].str.replace(',', '.')
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Bron: Inkomen als werknemer'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Bron: Inkomen als werknemer'].str.replace(',', '.')

In [38]:
# type van de kolommen omzetten naar floats
inkomen['Inkomen en vermogen|Particuliere huishoudens excl. studenten'] = inkomen['Inkomen en vermogen|Particuliere huishoudens excl. studenten'].astype(float)
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Particuliere huishoudens excl. studenten'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Particuliere huishoudens excl. studenten'].astype(float)
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenpersoonshuishouden'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenpersoonshuishouden'].astype(float)
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenoudergezin'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenoudergezin'].astype(float)
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, zonder kind'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, zonder kind'].astype(float)
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, met kind(eren)'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, met kind(eren)'].astype(float)
inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Bron: Inkomen als werknemer'] = inkomen['Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Bron: Inkomen als werknemer'].astype(float)

In [39]:
# 'Inkomen en vermogen|Particuliere huishoudens excl. studenten', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Particuliere huishoudens excl. studenten', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenpersoonshuishouden', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenoudergezin', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, zonder kind', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, met kind(eren)', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Bron: Inkomen als werknemer'

In [40]:
# kolommen selecteren
inkomen = inkomen[['Unnamed: 0', 'Inkomen en vermogen|Particuliere huishoudens excl. studenten', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Particuliere huishoudens excl. studenten', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenpersoonshuishouden', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenoudergezin', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, zonder kind', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, met kind(eren)', 'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Bron: Inkomen als werknemer']]

In [41]:
# namen van kolommen aanpassen
inkomen.rename(columns={'Unnamed: 0': 'provincie',
                        'Inkomen en vermogen|Particuliere huishoudens excl. studenten':'particuliere huishoudens excl. studenten', 
                        'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Particuliere huishoudens excl. studenten':'particuliere huishoudens excl. studenten, gem. besteedbaar inkomen', 
                        'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenpersoonshuishouden': 'eenpersoons- huishouden, gem. besteedbaar inkomen', 
                        'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Eenoudergezin': 'eenouder- gezin, gem. besteedbaar inkomen',
                        'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, zonder kind': 'paar zonder kind, gem. besteedbaar inkomen', 
                        'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Type: Paar, met kind(eren)':'paar met kinderen, gem. besteedbaar inkomen', 
                        'Inkomen en vermogen|Inkomen van particuliere huishoudens|Gemiddeld besteedbaar inkomen|Bron: Inkomen als werknemer':'inkomen als werknemer, gem. besteedbaar inkomen' }, inplace = True)

### Aantal mensen per regio
De kleuren zouden overal nog kunnen worden aangepast

In [42]:
# kolommen weg halen
del aantal_mensen["Unnamed: 2"] 
del aantal_mensen["Onderwerp"]
del aantal_mensen['2020']
#rijen weg halen
aantal_mensen = aantal_mensen.drop(index=13)

In [43]:
# kolom namen aanpassen
aantal_mensen.rename(columns={"Regio's": 'provincie',
                             '2019': 'pop_2019'}, inplace=True)

### Opleidingen per regio

In [44]:
# rijen verwijderen
opleiding = opleiding.drop(index=14)
opleiding = opleiding.drop(index=15)
opleiding = opleiding.drop(index=16)
opleiding = opleiding.drop(index=17)
opleiding = opleiding.drop(index=18)
opleiding = opleiding.drop(index=19)
opleiding = opleiding.drop(index=20)
opleiding = opleiding.drop(index=21)
opleiding = opleiding.drop(index=22)
opleiding = opleiding.drop(index=23)
opleiding = opleiding.drop(index=24)
opleiding = opleiding.drop(index=25)
opleiding = opleiding.drop(index=26)
opleiding = opleiding.drop(index=27)
opleiding = opleiding.drop(index=28)
opleiding = opleiding.drop(index=29)
opleiding = opleiding.drop(index=30)
opleiding = opleiding.drop(index=31)

opleiding.reset_index(inplace=True)

In [45]:
# aanpassen de namen van rijen
opleiding.rename(columns={'0': 'provincie'}, inplace = True)

In [46]:
# kolommen selecteren
opleiding = opleiding[['provincie', 'Totaal voortgezet onderwijs (vo)', 'Vavo', 'Totaal mbo (incl. extranei)',
                      'Hbo-associate degree', 'Hbo-bachelor', 'Hbo-master/vervolgopleiding', 'Wo-bachelor',
                      'Wo-master', 'Wo-doctoraal', 'Wo-vervolgopleiding']]

In [47]:
opleiding['Totaal voortgezet onderwijs (vo)'] = opleiding['Totaal voortgezet onderwijs (vo)'].astype(float)
opleiding['Vavo']=opleiding['Vavo'].astype(float)
opleiding['Totaal mbo (incl. extranei)'] = opleiding['Totaal mbo (incl. extranei)'].astype(float)
opleiding['Hbo-associate degree'] = opleiding['Hbo-associate degree'].astype(float)
opleiding['Hbo-bachelor'] = opleiding['Hbo-bachelor'].astype(float)
opleiding['Hbo-master/vervolgopleiding'] = opleiding['Hbo-master/vervolgopleiding'].astype(float)
opleiding['Wo-bachelor'] = opleiding['Wo-bachelor'].astype(float)
opleiding['Wo-master'] = opleiding['Wo-master'].astype(float)
opleiding['Wo-doctoraal'] = opleiding['Wo-doctoraal'].astype(float)
opleiding['Wo-vervolgopleiding'] = opleiding['Wo-vervolgopleiding'].astype(float)

In [48]:
# Opleidingen samenvoegen
opleiding['Hbo'] = opleiding['Hbo-associate degree']+opleiding['Hbo-bachelor']+opleiding['Hbo-master/vervolgopleiding']
opleiding['Hbo']

0     74924.0
1      3549.0
2      2798.0
3      1479.0
4      5491.0
5      1497.0
6      8556.0
7      5746.0
8     10397.0
9     14365.0
10     1210.0
11    12448.0
12     4279.0
13     3109.0
Name: Hbo, dtype: float64

### Geo

In [49]:
geo_df = geo_df[['PROV_NAAM', 'geometry']] # kolommen selecteren

# Dataset mergen
De datasets populatie, inkomen en opleiding worden samengevoegd.

In [50]:
populatie_inkomen = aantal_mensen.merge(inkomen)

In [51]:
df_zondergeo = populatie_inkomen.merge(opleiding)

In [52]:
df=pd.merge(df_zondergeo, geo_df, how = 'inner', left_on = 'provincie', right_on = 'PROV_NAAM', validate = 'many_to_one')

In [53]:
df

,provincie,pop_2019,particuliere huishoudens excl. studenten,"particuliere huishoudens excl. studenten, gem. besteedbaar inkomen","eenpersoons- huishouden, gem. besteedbaar inkomen","eenouder- gezin, gem. besteedbaar inkomen","paar zonder kind, gem. besteedbaar inkomen","paar met kinderen, gem. besteedbaar inkomen","inkomen als werknemer, gem. besteedbaar inkomen",Totaal voortgezet onderwijs (vo),...,Hbo-associate degree,Hbo-bachelor,Hbo-master/vervolgopleiding,Wo-bachelor,Wo-master,Wo-doctoraal,Wo-vervolgopleiding,Hbo,PROV_NAAM,geometry
0,Groningen (PV),583990.0,263.9,39.2,23.6,34.2,44.4,61.2,44.8,5546.0,...,130.0,3245.0,174.0,3122.0,2507.0,0.0,312.0,3549.0,Groningen (PV),"POLYGON ((238550.838 621182.664, 237986.290 62..."
1,Fryslân (PV),647672.0,285.2,41.6,24.2,35.7,44.4,62.2,46.8,7712.0,...,140.0,2494.0,164.0,289.0,314.0,0.0,44.0,2798.0,Fryslân (PV),"POLYGON ((219088.577 615550.321, 219043.135 61..."
2,Drenthe (PV),492167.0,215.8,43.3,24.7,36.2,45.6,63.3,49.5,5885.0,...,110.0,1295.0,74.0,214.0,183.0,0.0,21.0,1479.0,Drenthe (PV),"POLYGON ((229985.506 579739.846, 229780.728 57..."
3,Overijssel (PV),1156431.0,488.1,44.0,24.5,36.2,45.7,64.7,49.3,14597.0,...,169.0,5074.0,248.0,1294.0,1374.0,0.0,151.0,5491.0,Overijssel (PV),"POLYGON ((205507.439 539349.688, 205241.862 53..."
4,Flevoland (PV),416546.0,170.5,45.3,25.3,36.3,48.6,63.4,50.3,5198.0,...,140.0,1305.0,52.0,327.0,286.0,0.0,34.0,1497.0,Flevoland (PV),"POLYGON ((182139.661 535337.499, 182088.641 53..."
5,Gelderland (PV),2071972.0,888.9,45.4,25.2,37.5,48.4,67.2,50.4,24653.0,...,328.0,7854.0,374.0,3797.0,4127.0,0.0,458.0,8556.0,Gelderland (PV),"POLYGON ((192593.176 498989.542, 192161.428 49..."
6,Utrecht (PV),1342158.0,576.6,49.6,27.4,39.9,54.2,74.5,54.2,15782.0,...,162.0,5229.0,355.0,4001.0,4212.0,0.0,503.0,5746.0,Utrecht (PV),"POLYGON ((130188.800 477178.044, 130070.000 47..."
7,Noord-Holland (PV),2853359.0,1312.7,47.1,27.6,38.9,53.5,74.8,52.7,29578.0,...,240.0,9582.0,575.0,6552.0,7507.0,0.0,920.0,10397.0,Noord-Holland (PV),"POLYGON ((154328.670 530832.170, 151670.410 53..."
8,Zuid-Holland (PV),3673893.0,1628.7,45.3,26.2,36.6,50.6,69.8,51.3,38947.0,...,907.0,12601.0,857.0,9532.0,10124.0,0.0,828.0,14365.0,Zuid-Holland (PV),"POLYGON ((97728.934 481002.808, 96586.793 4815..."
9,Zeeland (PV),383032.0,172.4,43.4,25.4,36.5,46.6,65.4,49.4,4078.0,...,93.0,1068.0,49.0,242.0,92.0,0.0,7.0,1210.0,Zeeland (PV),"POLYGON ((50564.929 418784.380, 50331.602 4188..."
10,Noord-Brabant (PV),2544806.0,1113.3,46.3,25.9,38.2,49.0,69.6,51.5,28188.0,...,840.0,11071.0,537.0,3588.0,4254.0,0.0,180.0,12448.0,Noord-Brabant (PV),"POLYGON ((165188.661 425343.807, 164332.809 42..."
11,Limburg (PV),1116137.0,509.7,42.2,24.4,35.9,45.6,64.7,49.1,10369.0,...,205.0,3886.0,188.0,1954.0,1868.0,0.0,200.0,4279.0,Limburg (PV),"POLYGON ((192885.659 417113.722, 192773.960 41..."

## Percentages van opleiding

In [54]:
df['pop_2019']
df.columns

Index(['provincie', 'pop_2019', 'particuliere huishoudens excl. studenten',
       'particuliere huishoudens excl. studenten, gem. besteedbaar inkomen',
       'eenpersoons- huishouden, gem. besteedbaar inkomen',
       'eenouder- gezin, gem. besteedbaar inkomen',
       'paar zonder kind, gem. besteedbaar inkomen',
       'paar met kinderen, gem. besteedbaar inkomen',
       'inkomen als werknemer, gem. besteedbaar inkomen',
       'Totaal voortgezet onderwijs (vo)', 'Vavo',
       'Totaal mbo (incl. extranei)', 'Hbo-associate degree', 'Hbo-bachelor',
       'Hbo-master/vervolgopleiding', 'Wo-bachelor', 'Wo-master',
       'Wo-doctoraal', 'Wo-vervolgopleiding', 'Hbo', 'PROV_NAAM', 'geometry'],
      dtype='object')

In [55]:
df['Totaal voortgezet onderwijs (vo)_p']=df['Totaal voortgezet onderwijs (vo)']/df['pop_2019']*100
df['Totaal mbo (incl. extranei)_p'] = df['Totaal mbo (incl. extranei)']/df['pop_2019']*100
df['Vavo_p'] = df['Vavo']/df['pop_2019']*100
df['Totaal mbo (incl. extranei)_p'] = df['Totaal mbo (incl. extranei)']/df['pop_2019']*100
df['Hbo-associate degree_p'] = df['Hbo-associate degree']/df['pop_2019']*100
df['Hbo-bachelor_p'] = df['Hbo-bachelor']/df['pop_2019']*100
df['Hbo-master/vervolgopleiding_p'] = df['Hbo-master/vervolgopleiding']/df['pop_2019']*100
df['Wo-bachelor_p'] = df['Wo-bachelor']/df['pop_2019']*100
df['Wo-master_p'] = df['Wo-master']/df['pop_2019']*100
df['Wo-doctoraal_p'] = df['Wo-doctoraal']/df['pop_2019']*100
df['Wo-vervolgopleiding_p'] = df['Wo-vervolgopleiding']/df['pop_2019']*100

## Opleidingen samenvoegen
Hbo en Wo

In [56]:
df['Hbo'] = df['Hbo-associate degree']+ df['Hbo-bachelor'] + df['Hbo-master/vervolgopleiding']
df['Wo'] = df['Wo-bachelor']+df['Wo-master']+df['Wo-doctoraal']+df['Wo-vervolgopleiding']
df.head()

,provincie,pop_2019,particuliere huishoudens excl. studenten,"particuliere huishoudens excl. studenten, gem. besteedbaar inkomen","eenpersoons- huishouden, gem. besteedbaar inkomen","eenouder- gezin, gem. besteedbaar inkomen","paar zonder kind, gem. besteedbaar inkomen","paar met kinderen, gem. besteedbaar inkomen","inkomen als werknemer, gem. besteedbaar inkomen",Totaal voortgezet onderwijs (vo),...,Totaal mbo (incl. extranei)_p,Vavo_p,Hbo-associate degree_p,Hbo-bachelor_p,Hbo-master/vervolgopleiding_p,Wo-bachelor_p,Wo-master_p,Wo-doctoraal_p,Wo-vervolgopleiding_p,Wo
0,Groningen (PV),583990.0,263.9,39.2,23.6,34.2,44.4,61.2,44.8,5546.0,...,1.010634,0.040412,0.022261,0.555660,0.029795,0.534598,0.429288,0.0,0.053426,5941.0
1,Fryslân (PV),647672.0,285.2,41.6,24.2,35.7,44.4,62.2,46.8,7712.0,...,1.146414,0.045239,0.021616,0.385071,0.025321,0.044621,0.048481,0.0,0.006794,647.0
2,Drenthe (PV),492167.0,215.8,43.3,24.7,36.2,45.6,63.3,49.5,5885.0,...,1.079512,0.046123,0.022350,0.263122,0.015036,0.043481,0.037183,0.0,0.004267,418.0
3,Overijssel (PV),1156431.0,488.1,44.0,24.5,36.2,45.7,64.7,49.3,14597.0,...,1.107373,0.045744,0.014614,0.438764,0.021445,0.111896,0.118814,0.0,0.013057,2819.0
4,Flevoland (PV),416546.0,170.5,45.3,25.3,36.3,48.6,63.4,50.3,5198.0,...,1.198427,0.048254,0.033610,0.313291,0.012484,0.078503,0.068660,0.0,0.008162,647.0

# Dataset opslaan in csv

In [60]:
df.to_csv('Opleiding_inkomen.csv', index = False)